spring:
  profiles:
    active: dev
  application:
    name: cloud-config-client
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka,http://eureka6003.com:6003/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

---
spring:
  profiles: dev
server:
  port: 8082

info:
  version: 2

---
spring:
  profiles: test
server:
  port: 8083
