spring:
  profiles:
    active: dev
  application:
    name: cloud-provider
server:
  port: 8080

info:
  version: 1.0

---
spring:
  profiles: prod
server:
  port: 8081

info:
  version: 1.0

---
spring:
  profiles: dev
server:
  port: 8082

info:
  version: 2.0

---
spring:
  profiles: test
server:
  port: 8083

info:
  version: 1.0
