server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: cloud-config-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka,http://eureka6003.com:6003/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true



---
spring:
  profiles: dev
server:
  port: 8002

info:
  version: 1.0

---
spring:
  profiles: test
server:
  port: 8003
